function [fitresult, gof] = createFit(XDATA2, YDATA2)
%CREATEFIT(XDATA2,YDATA2)
%  Create a fit.
%
%  Data for 'Gaussian5' fit:
%      X Input : XDATA2
%      Y Output: YDATA2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Sep-2017 13:48:49


%% Fit: 'Gaussian5'.
clear
load('SAMPLE2.mat')
for n=1:29
XDATA2(1,n)=SAMPLE2(1,n);
YDATA2(1,n)=SAMPLE2(2,n);
end

[xData, yData] = prepareCurveData( XDATA2, YDATA2 );

% Set up fittype and options.
ft = fittype( 'gauss5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [1169.6 -3.88 1.95538113195509 1140.3999982135 4.93 1.0192350819011 1117.19230409608 0 0.65929315605257 1093.08657277356 1.47 0.579639784889827 1020.83719680363 3.06 0.725439030639096];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Gaussian5' );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'v vs. I', 'Gaussian5', 'Lower bounds (Gaussian5)', 'Upper bounds (Gaussian5)', 'Location', 'SouthWest' );
% Label axes
xlabel 'v, speed'
ylabel 'I, intensity'
grid on


