function [fitresult, gof] = createFit(XDATA1, YDATA1)
%CREATEFIT(XDATA1,YDATA1)
%  Create a fit.
%
%  Data for 'Gaussian3' fit:
%      X Input : XDATA1
%      Y Output: YDATA1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Sep-2017 10:25:53
%% Fit: 'Gaussian3'.

clear
load('SAMPLE1.mat')
for n=1:28
XDATA1(1,n)=SAMPLE1(1,n);
YDATA1(1,n)=SAMPLE1(2,n);
end

[xData, yData] = prepareCurveData( XDATA1, YDATA1 );

% Set up fittype and options.
ft = fittype( 'gauss3' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [2532.2 -2.41 3.15173264067585 2463.03210618082 4.57 1.10856962566445 2008.97623182275 2.78 1.00191279283782];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Gaussian3' );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'v vs. I', 'Gaussian3', 'Lower bounds (Gaussian3)', 'Upper bounds (Gaussian3)', 'Location', 'SouthWest' );
% Label axes
xlabel 'v, speed'
ylabel 'I, intensity'
grid on


