function [fitresult, gof] = createFit(XDATA4, YDATA4)
%CREATEFIT(XDATA4,YDATA4)
%  Create a fit.
%
%  Data for 'Gaussian6' fit:
%      X Input : XDATA4
%      Y Output: YDATA4
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Sep-2017 14:09:34


%% Fit: 'Gaussian6'.
clear
load('SAMPLE4.mat')
for n=1:30
XDATA4(1,n)=SAMPLE4(1,n);
YDATA4(1,n)=SAMPLE4(2,n);
end

[xData, yData] = prepareCurveData( XDATA4, YDATA4 );

% Set up fittype and options.
ft = fittype( 'gauss6' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [1960.6 -4.33 2.21937485260528 1952.49927225705 4.21 0.682860433095542 1877.39025423675 2.39 0.444327447490689 1723.13463452233 1.46 0.401776294927975 1434.67134142073 -1.26 0.708376474421694 1423.57953173569 0.66 0.45249220639424];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Gaussian6' );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'v vs. I', 'Gaussian6', 'Lower bounds (Gaussian6)', 'Upper bounds (Gaussian6)', 'Location', 'SouthWest' );
% Label axes
xlabel 'v, speed'
ylabel 'I, intensity'
grid on


